matrix_1 <- matrix(1:9,nrow=3,ncol=3)
matrix_2 <- matrix(9:1,nrow=3,ncol=3)
cat("Matrix-1 \n")
print(matrix_1)
cat("Matrix-2 \n")
print(matrix_2)
cat("Matrix Addition")
print(matrix_1+matrix_2)
cat("Matrix Substraction")
print(matrix_1-matrix_2)
cat("Matrix-1 Transpose")
print(t(matrix_1))
cat("Matrix-2 Transpose")
print(t(matrix_2))
